micronaut:
  application:
    name: musicalInstrumentsSubscrible
cassandra:
  default:
    clusterName: '"myCluster"'
    contactPoint: '"localhost"'
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true
kafka.bootstrap.servers: localhost:9092
